[tool.poetry]
name = "awesome-xontribs"
version = "0.1.0"
description = "Awesoe\b list of Xonsh contributions"
authors = ["Noortheen Raja <jnoortheen@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
mkdocs = "^1.3.0"
mkdocs-material = "^8.2.11"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
